role_mapping = {
    # 🎓 学生类
    "PhD student": "PhD Student",
    "PhD Student": "PhD Student",
    "Ph.D. Student": "PhD Student",
    "Ph.D Student": "PhD Student",
    "Ph.D. student": "PhD Student",
    "phd": "PhD Student",
    "Ph.D. candidate": "PhD Student",
    "PhD Candidate": "PhD Student",
    "Ph.D Candidate": "PhD Student",
    "Ph.D. Candidate": "PhD Student",
    "Ph. D candidate": "PhD Student",
    "Doctoral Student": "PhD Student",
    "Doctoral student": "PhD Student",
    "Doctoral Research Assistant": "PhD Student",
    "Doctoral Assistant": "PhD Student",
    "Doctoral": "PhD Student",
    "CS PhD Student": "PhD Student",
    "Graduate Student, PhD": "PhD Student",
    "Ph.D. Student Researcher": "PhD Student",

    "MS student": "Master Student",
    "MS Student": "Master Student",
    "Master Student": "Master Student",
    "Master's Student": "Master Student",
    "Master's student": "Master Student",
    "master": "Master Student",
    "M.Sc. Student": "Master Student",
    "M.S. in Electrical & Computer Engineering": "Master Student",
    "MSCS Student": "Master Student",
    "MEng student": "Master Student",
    "Master's candidate": "Master Student",

    "Undergraduate Student": "Undergraduate Student",
    "Undergrad student": "Undergraduate Student",
    "Undergraduate": "Undergraduate Student",
    "Undergraduate Researcher": "Undergraduate Student",
    "Undergraduate Research Assistant": "Undergraduate Student",

    "Graduate Student": "Graduate Student",
    "Graduate Student Researcher": "Graduate Student",
    "Graduate Research Assistant": "Graduate Student",
    "Graduate Research Associate": "Graduate Student",
    "Graduate Research Student": "Graduate Student",
    "Graduate Researcher": "Graduate Student",
    "Graduate Student Fellow": "Graduate Student",
    "Graduate Student Instructor": "Graduate Student",
    "Graduate Teaching Assistant": "Graduate Student",
    "Graduate Teaching Associate": "Graduate Student",
    "Graduate Service Assistant": "Graduate Student",
    "Graduate Teaching/Research Assistant": "Graduate Student",

    # 👨‍🏫 教师类
    "Professor": "Professor",
    "professor": "Professor",
    "Full Professor": "Professor",
    "Distinguished Professor": "Professor",
    "Professor (Research)": "Professor",
    "Zhiyuan Chair Professor": "Professor",
    "Chair Professor": "Professor",
    "Choh-Ming Li Chair Professor": "Professor",
    "Chair Professor of Computer Science": "Professor",
    "President's Chair Professor": "Professor",
    "John and Rebecca Moores Professor": "Professor",
    "John Cocke Distinguished Professor of Electrical and Computer Engineering": "Professor",
    "Peking University Chair Professor": "Professor",
    "KAIST Endowed Chair Professor": "Professor",
    "SUNY Distinguished Professor and Chair": "Professor",
    "Swire Professor of Aerospace Engineering": "Professor",
    "Guoqiang Professor": "Professor",
    "Short-Dooley Professor": "Professor",
    "Bloomberg Distinguished Professor": "Professor",
    "Bank of America Distinguished Professor": "Professor",
    "Michael Henry Strater University Professor": "Professor",
    "Forrest G. Hamrick Professor in Engineering, Emeritus": "Professor",
    "Distinguished Professor Emeritus": "Professor",
    "Professor Emeritus": "Professor",
    "Professor of Practice": "Professor",
    "Professor and Head": "Professor",
    "Professor of High Performance Computing Technologies": "Professor",
    "Presidential Young Professor": "Professor",

    "Associate Professor": "Associate Professor",
    "associate professor": "Associate Professor",
    "Tenure-Track Associate Professor": "Associate Professor",
    "Neubauer Associate Professor": "Associate Professor",
    "Noah Harding Associate Professor": "Associate Professor",
    "Elmore Associate Professor": "Associate Professor",
    "Pre-tenured Associate Professor": "Associate Professor",

    "Assistant Professor": "Assistant Professor",
    "Assistant Research Professor": "Assistant Professor",
    "Tenure-track Assistant Professor": "Assistant Professor",

    "Adjunct Professor": "Adjunct/Visiting Professor",
    "Visiting Professor": "Adjunct/Visiting Professor",
    "Affiliate Professor": "Adjunct/Visiting Professor",

    # 🔬 研究员/博士后类
    "Researcher": "Researcher",
    "Research Student": "Researcher",
    "Research Intern": "Researcher",
    "Research Assistant": "Researcher",
    "Assistant Researcher": "Researcher",
    "Research Associate": "Researcher",
    "Research Fellow": "Researcher",
    "Independent Researcher": "Researcher",
    "Unaffiliated Researcher": "Researcher",

    "Postdoc": "Postdoctoral Researcher",
    "PostDoc": "Postdoctoral Researcher",
    "Postdoctoral researcher": "Postdoctoral Researcher",
    "Postdoctoral Scholar": "Postdoctoral Researcher",
    "Postdoctoral Fellow": "Postdoctoral Researcher",
    "Postdoctoral Researcher": "Postdoctoral Researcher",
    "Postdoctoral Research Associate": "Postdoctoral Researcher",
    "Postdoctoral Research Fellow": "Postdoctoral Researcher",
    "Postdoctoral Associate": "Postdoctoral Researcher",
    "PostDoc Researcher": "Postdoctoral Researcher",

    "Research Scientist": "Research Scientist",
    "Sr. Research Scientist": "Research Scientist",
    "Principal Research Scientist": "Research Scientist",
    "Senior Research Scientist": "Research Scientist",
    "Staff Research Scientist": "Research Scientist",
    "Distinguished Research Scientist": "Research Scientist",
    "Research Staff Scientist": "Research Scientist",
    "Research Scientist Director": "Research Scientist",

    "Principal Researcher": "Researcher",
    "Senior Researcher": "Researcher",
    "Research Professor": "Researcher",

    # 🛠 工程师类（按职级）
    "Engineer": "Engineer",
    "Software Engineer": "Engineer",
    "Research Engineer": "Engineer",
    "Algorithm Engineer": "Engineer",
    "System Engineer": "Engineer",
    "Computer Architect": "Engineer",
    "Deep Learning Engineer": "Engineer",
    "AI Engineer": "Engineer",
    "ML Engineer": "Engineer",
    "Research Software Engineer": "Engineer",
    "Research SDE": "Engineer",
    "IDC Engineer": "Engineer",
    "Algorithm Research Intern": "Engineer",
    "Processing-in-Memory software engineer": "Engineer",
    "Engineer I": "Engineer",

    "Staff Engineer": "Mid-level Engineer",
    "Staff Software Engineer": "Mid-level Engineer",
    "Staff AI Engineer": "Mid-level Engineer",
    "Research Staff Member": "Mid-level Engineer",
    "Senior Research Engineer": "Mid-level Engineer",
    "Senior RSDE": "Mid-level Engineer",
    "Research Development Software Engineer": "Mid-level Engineer",
    "Research Engineer-II": "Mid-level Engineer",

    "Senior Engineer": "Senior Engineer",
    "Senior Software Engineer": "Senior Engineer",
    "Senior Research SDE": "Senior Engineer",
    "Senior Staff Engineer": "Senior Engineer",
    "Senior Staff Software Engineer": "Senior Engineer",
    "Senior Machine Learning Engineer": "Senior Engineer",
    "Senior Deep Learning Researcher": "Senior Engineer",
    "Senior Research Hardware Dev. Engineer": "Senior Engineer",
    "Senior Systems Research Engineer": "Senior Engineer",
    "Senior Development Engineer": "Senior Engineer",
    "Senior Technical Expert": "Senior Engineer",

    "Principal Engineer": "Principal Engineer",
    "Principal Software Engineer": "Principal Engineer",
    "Principal Research Engineer": "Principal Engineer",
    "Principal Research Scientist": "Principal Engineer",
    "Principal Architect": "Principal Engineer",
    "Principal Scientist": "Principal Engineer",
    "Senior Principal Research Engineer": "Principal Engineer",
    "Senior Principal Applied Scientist": "Principal Engineer",
    "Principal AI Researcher": "Principal Engineer",
    "Senior Principal Researcher": "Principal Engineer",

    "Distinguished Engineer": "Distinguished Engineer",
    "Senior Distinguished Engineer": "Distinguished Engineer",
    "Distinguished Software Engineer": "Distinguished Engineer",
    "Distinguished AI Engineer": "Distinguished Engineer",
}
